### ISSUE TITLE
Email field formatting Issue

### ISSUE THREAD

**Issue by dmrx** [SalesforceLabs/EnhancedLightningGrid#1]
When using email fields  (in this case the standard contact email) we are seeing inconsistent reading of the field type -- sometimes it's formatted correctly as EMAIL other times not. 

We cannot identify what the email formatting issue is that is causing this issue ( as shown below).
Email for Jake Snake is link to 'jake.snake' then 'test.com'. There is no 'mailto:' link.

<img width="510" alt="screen shot 2018-05-01 at 2 34 38 pm" src="https://user-images.githubusercontent.com/2776470/39494860-dc171c80-4d4c-11e8-94b8-122698ac9c7e.png">

**Comment by MarioVanDenEijnde** [comment]
Hello dmrx,

I am trying to do some customizations and try to repackage this solution but run into failures. I opened an issue 'test'.

Maybe you can advise how to repackage this?

Kind regards,
Mario

**Comment by dmrx** [comment]
Across our sandboxes,  this issue seems to have been fixed with the Summer '18 release.  Closing ticket.
