### ISSUE TITLE
Understanding Actions

### ISSUE THREAD

**Issue by ezrafischer** [SalesforceLabs/EnhancedLightningGrid#27]
Hi,

I'm looking for more documentation on creating custom actions in the EnhancedLightningGrid. I'm specifically trying to create a row button on an Order Line Item that lets a user edit just the quantity field on that OrderItem.

Thanks,
Ezra

**Comment by greier** [comment]
Hi,

you need to create a custom event and triggered it using the following:

**Event:**
<aura:event type="APPLICATION" description="CustomEventName">
</aura:event>

**Row Button**, e.g.:
Event: e.c:CustomEventName
Payload:
{
"objectId":"#Id#",
"parentObjectId":"#parentrecordId#",
"otherStuff":"otherAttribute"
}


**Custom Component** placed anywhere on the page:
<aura:component description="Custom_Actions"
              implements="flexipage:availableForRecordHome,flexipage:availableForAllPageTypes,force:hasRecordId"
                access="global">
    <aura:handler event="c:CustomEventName" action="{!c.handleApplicationEvent}"/>
</aura:component>

**JS Controller:**
({
    handleApplicationEvent: function (cmp, event) {

        var parentObjectId = event.getParam("parentObjectId");
        var objectId = event.getParam("objectId"); 
        var otherStuff = event.getParam("otherStuff"); 

      
//DO STH. HERE, e.g. record form with the 2 fields you need to change and pop it open in a modal.
       
 
    }
})


hth
matthias

**Comment by ezrafischer** [comment]
Wow -- thank you!!
