### ISSUE TITLE
Appexchange package is outdated 

### ISSUE THREAD

**Issue by romcode** [SalesforceLabs/EnhancedLightningGrid#8]
Hi, it seems appexhange package last update was on 1/28/2018, which means last fixes are missing there. 

Would you mind pushing it?

Thanks!

**Comment by justinclarke-sc** [comment]
Hello! I got in touch with some folks at SF and they have updated the Github with the source code from the latest AppExchange version.

**Comment by mcarrilloatsalesforcedotcom** [comment]
Package and source recently updated, Nov 2022
